// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC07CrearhorariodeclaseTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC07Crearhorariodeclase() {
    driver.Navigate().GoToUrl("http://25.76.110.243:8030/");
    driver.FindElement(By.LinkText("Class Room Allocation")).Click();
    driver.FindElement(By.LinkText("Allocate Classroom")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.Id("DepartmentId-error")).Text, Is.EqualTo("Please select department!"));
    Assert.That(driver.FindElement(By.Id("CourseId-error")).Text, Is.EqualTo("Please Select Course!"));
    Assert.That(driver.FindElement(By.Id("RoomId-error")).Text, Is.EqualTo("Please Select room!"));
    Assert.That(driver.FindElement(By.Id("DayId-error")).Text, Is.EqualTo("Please Select day!"));
    Assert.That(driver.FindElement(By.Id("StartTime-error")).Text, Is.EqualTo("Select Start time!"));
    Assert.That(driver.FindElement(By.Id("Endtime-error")).Text, Is.EqualTo("Please select End time!"));
    driver.FindElement(By.CssSelector(".body-content")).Click();
    driver.FindElement(By.Id("DepartmentId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Artesanía']")).Click();
    }
    driver.FindElement(By.Id("DepartmentId")).Click();
    driver.FindElement(By.Id("CourseId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("CourseId"));
      dropdown.FindElement(By.XPath("//option[. = '453214']")).Click();
    }
    driver.FindElement(By.Id("CourseId")).Click();
    driver.FindElement(By.Id("RoomId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("RoomId"));
      dropdown.FindElement(By.XPath("//option[. = 'Room No:101']")).Click();
    }
    driver.FindElement(By.Id("RoomId")).Click();
    driver.FindElement(By.Id("DayId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("DayId"));
      dropdown.FindElement(By.XPath("//option[. = 'Monday']")).Click();
    }
    driver.FindElement(By.Id("DayId")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(5) > .control-label")).Click();
    driver.FindElement(By.CssSelector(".dwwl1 > .dwwbm > span")).Click();
    driver.FindElement(By.CssSelector(".dwwl1 > .dwwbm > span")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".dwwl1 > .dwwbm > span"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".dwwl1 > .dwwbm > span")).Click();
    driver.FindElement(By.CssSelector(".dwwl2 > .dwwbm > span")).Click();
    driver.FindElement(By.LinkText("Set")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(6) > .control-label")).Click();
    driver.FindElement(By.CssSelector(".dwwl0 > .dwwbp > span")).Click();
    driver.FindElement(By.CssSelector(".dwwl0 > .dwwbp > span")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".dwwl0 > .dwwbp > span"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.CssSelector(".dwwl1 > .dwwbp > span")).Click();
    driver.FindElement(By.CssSelector(".dwwl1 > .dwwbp > span")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".dwwl1 > .dwwbp > span"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.LinkText("Set")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector("p:nth-child(5)")).Text, Is.EqualTo("Saved Successfully !"));
    driver.FindElement(By.LinkText("Class Room Allocation")).Click();
    driver.FindElement(By.LinkText("View Class Schedule")).Click();
    driver.FindElement(By.Id("DepartmentId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Artesanía']")).Click();
    }
        driver.FindElement(By.Id("DepartmentId")).Click();
        Assert.That(driver.FindElement(By.CssSelector("tbody:nth-child(2) td:nth-child(1)")).Text, Is.EqualTo("453214"));
        Assert.That(driver.FindElement(By.CssSelector("tbody:nth-child(2) td:nth-child(2)")).Text, Is.EqualTo("Moldaje"));
        driver.Close();
  }
}
