// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC10VerNotasdelestudianteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC10VerNotasdelestudiante() {
    driver.Navigate().GoToUrl("http://25.76.110.243:8030/");
    driver.FindElement(By.LinkText("Student")).Click();
    driver.FindElement(By.LinkText("View Result")).Click();
    driver.FindElement(By.Id("StudentId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("StudentId"));
      dropdown.FindElement(By.XPath("//option[. = '22-2020-001']")).Click();
    }
    driver.FindElement(By.Id("StudentId")).Click();
    {
      string value = driver.FindElement(By.Id("Name")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("Hugo Jimenez"));
    }
    {
      string value = driver.FindElement(By.Id("Email")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("jim22@gmail.com"));
    }
    {
      string value = driver.FindElement(By.Id("Department")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("Salud"));
    }
    {
      string value = driver.FindElement(By.Id("Department")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("Salud"));
    }
    {
      var element = driver.FindElement(By.Id("Name"));
      Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
      Assert.False(isEditable);
    }
    {
      var element = driver.FindElement(By.Id("Email"));
      Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
      Assert.False(isEditable);
    }
    {
      var element = driver.FindElement(By.Id("Department"));
      Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
      Assert.False(isEditable);
    }
    Assert.That(driver.FindElement(By.CssSelector("#myData td:nth-child(1)")).Text, Is.EqualTo("1166995"));
    Assert.That(driver.FindElement(By.CssSelector("#myData td:nth-child(2)")).Text, Is.EqualTo("Enfermeria"));
    Assert.That(driver.FindElement(By.CssSelector("#myData td:nth-child(3)")).Text, Is.EqualTo("A+"));
  }
}
