// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC03CrearcursoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC03Crearcurso() {
    driver.Navigate().GoToUrl("http://25.76.110.243:8030/");
    driver.FindElement(By.LinkText("Department")).Click();
    driver.FindElement(By.LinkText("Save Department")).Click();
    driver.FindElement(By.Id("Code")).Click();
    driver.FindElement(By.Id("Code")).SendKeys("31");
    driver.FindElement(By.Id("Name")).Click();
    driver.FindElement(By.Id("Name")).SendKeys("Química");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector("form > p")).Text, Is.EqualTo("Saved Successfully"));
    driver.FindElement(By.LinkText("Course")).Click();
    driver.FindElement(By.LinkText("Save Course")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.Id("Code-error")).Text, Is.EqualTo("Please enter a valid Course Code!"));
    Assert.That(driver.FindElement(By.Id("Name-error")).Text, Is.EqualTo("Please enter the valid Course Name!"));
    Assert.That(driver.FindElement(By.Id("Credit-error")).Text, Is.EqualTo("Credit is required!"));
    Assert.That(driver.FindElement(By.Id("Description-error")).Text, Is.EqualTo("Write something about course!"));
    Assert.That(driver.FindElement(By.Id("DepartmentId-error")).Text, Is.EqualTo("Please select related department!"));
    Assert.That(driver.FindElement(By.Id("SemesterId-error")).Text, Is.EqualTo("Please select related semester!"));
    driver.FindElement(By.Id("Code")).Click();
    driver.FindElement(By.Id("Code")).SendKeys("564378");
    driver.FindElement(By.Id("Name")).Click();
    driver.FindElement(By.Id("Name")).SendKeys("Quimica avanzado");
    driver.FindElement(By.Id("Credit")).Click();
    driver.FindElement(By.Id("Credit")).SendKeys("4");
    driver.FindElement(By.Id("Description")).Click();
    driver.FindElement(By.Id("Description")).SendKeys("Este curso pertenece a quimica");
    driver.FindElement(By.Id("DepartmentId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Química']")).Click();
    }
    driver.FindElement(By.Id("DepartmentId")).Click();
    driver.FindElement(By.Id("SemesterId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("SemesterId"));
      dropdown.FindElement(By.XPath("//option[. = '1st']")).Click();
    }
    driver.FindElement(By.Id("SemesterId")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector("p:nth-child(4)")).Text, Is.EqualTo("Saved Successfully"));
    driver.FindElement(By.LinkText("Course")).Click();
    driver.FindElement(By.LinkText("View Course Statics")).Click();
    driver.FindElement(By.Id("DepartmentId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Química']")).Click();
    }
    driver.FindElement(By.Id("DepartmentId")).Click();
    Assert.That(driver.FindElement(By.CssSelector("td:nth-child(1)")).Text, Is.EqualTo("564378"));
    Assert.That(driver.FindElement(By.CssSelector("td:nth-child(2)")).Text, Is.EqualTo("Quimica avanzado"));
    Assert.That(driver.FindElement(By.CssSelector("td:nth-child(3)")).Text, Is.EqualTo("1st"));
    Assert.That(driver.FindElement(By.CssSelector("td:nth-child(4)")).Text, Is.EqualTo("Not Assigned yet"));
    driver.Close();
  }
}
