// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC04CrearprofesorTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC04Crearprofesor() {
    driver.Navigate().GoToUrl("http://25.76.110.243:8030/");
    driver.FindElement(By.LinkText("Department")).Click();
    driver.FindElement(By.LinkText("Save Department")).Click();
    driver.FindElement(By.Id("Code")).Click();
    driver.FindElement(By.Id("Code")).SendKeys("04");
    driver.FindElement(By.Id("Name")).Click();
    driver.FindElement(By.Id("Name")).SendKeys("Matematica");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector("form > p")).Text, Is.EqualTo("Saved Successfully"));
    driver.FindElement(By.LinkText("Teacher")).Click();
    driver.FindElement(By.LinkText("Save Teacher")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.Id("Name-error")).Text, Is.EqualTo("Please enter the Name"));
    Assert.That(driver.FindElement(By.Id("Address-error")).Text, Is.EqualTo("Address is required!"));
    Assert.That(driver.FindElement(By.Id("Email-error")).Text, Is.EqualTo("Please email address is required"));
    Assert.That(driver.FindElement(By.Id("Contact-error")).Text, Is.EqualTo("Please enter the contact"));
    Assert.That(driver.FindElement(By.Id("DesignationId-error")).Text, Is.EqualTo("Designation is required!"));
    Assert.That(driver.FindElement(By.Id("DepartmentId-error")).Text, Is.EqualTo("Please select department"));
    driver.FindElement(By.Id("Name")).Click();
    driver.FindElement(By.Id("Name")).SendKeys("Luisa Jimenez");
    driver.FindElement(By.Id("Address")).Click();
    driver.FindElement(By.Id("Address")).SendKeys("Heredia");
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("luisa20@gmail.com");
    driver.FindElement(By.Id("Contact")).Click();
    driver.FindElement(By.Id("Contact")).SendKeys("88888888");
    driver.FindElement(By.Id("DesignationId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("DesignationId"));
      dropdown.FindElement(By.XPath("//option[. = 'Professor']")).Click();
    }
    driver.FindElement(By.Id("DepartmentId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Matematica']")).Click();
    }
    driver.FindElement(By.Id("CreditTobeTaken")).Click();
    driver.FindElement(By.Id("CreditTobeTaken")).SendKeys("1");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector("p:nth-child(4)")).Text, Is.EqualTo("Saved Sucessfully"));
    driver.Close();
  }
}
