// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC06CrearestudianteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC06Crearestudiante() {
    driver.Navigate().GoToUrl("http://25.76.110.243:8030/");
    driver.FindElement(By.LinkText("Department")).Click();
    driver.FindElement(By.LinkText("Save Department")).Click();
    driver.FindElement(By.Id("Code")).Click();
    driver.FindElement(By.Id("Code")).SendKeys("05");
    driver.FindElement(By.Id("Name")).Click();
    driver.FindElement(By.Id("Name")).SendKeys("Ingieneria");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector("form > p")).Text, Is.EqualTo("Saved Successfully"));
    driver.FindElement(By.LinkText("Student")).Click();
    driver.FindElement(By.LinkText("Register Student")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.Id("Name-error")).Text, Is.EqualTo("Please enter the student Name"));
    Assert.That(driver.FindElement(By.Id("Email-error")).Text, Is.EqualTo("Please email address is required"));
    Assert.That(driver.FindElement(By.Id("Contact-error")).Text, Is.EqualTo("Please enter the student contact"));
    Assert.That(driver.FindElement(By.Id("Address-error")).Text, Is.EqualTo("Address is required!"));
    Assert.That(driver.FindElement(By.Id("DepartmentId-error")).Text, Is.EqualTo("Please select department"));
    driver.FindElement(By.Id("Name")).Click();
    driver.FindElement(By.Id("Name")).SendKeys("Fabian Gutierrez");
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("fabianjim20@gmail.com");
    driver.FindElement(By.Id("Contact")).Click();
    driver.FindElement(By.Id("Contact")).SendKeys("88888888");
    driver.FindElement(By.Id("RegDate")).Click();
    driver.FindElement(By.Id("RegDate")).SendKeys("12/8/1997");
    driver.FindElement(By.LinkText("1")).Click();
    driver.FindElement(By.Id("Address")).Click();
    driver.FindElement(By.Id("Address")).SendKeys("Heredia");
    driver.FindElement(By.Id("DepartmentId")).Click();
    {
      var dropdown = driver.FindElement(By.Id("DepartmentId"));
      dropdown.FindElement(By.XPath("//option[. = 'Ingieneria']")).Click();
    }
    driver.FindElement(By.Id("DepartmentId")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".body-content:nth-child(5)")).Text, Is.EqualTo("Saved Successfully!\r\nRegistration No:05-2020-001\r\nName:Fabian Gutierrez\r\nEmail:fabianjim20@gmail.com\r\nContact Number:88888888"));
    driver.Close();
  }
}
