// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC08RegistrarestudianteenuncursoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {

    driver.Quit();
  }
  [Test]
  public void tC08Registrarestudianteenuncurso() {
    driver.Navigate().GoToUrl("http://25.76.110.243:8030/");
        driver.FindElement(By.LinkText("Student")).Click();
        driver.FindElement(By.LinkText("Enroll Student In A Course")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        Assert.That(driver.FindElement(By.Id("StudentId-error")).Text, Is.EqualTo("Please select student Registration No"));
        Assert.That(driver.FindElement(By.Id("CourseId-error")).Text, Is.EqualTo("Please select Course"));
        driver.FindElement(By.Id("StudentId")).Click();
        {
            var dropdown = driver.FindElement(By.Id("StudentId"));
            dropdown.FindElement(By.XPath("//option[. = '19-2020-001']")).Click();
        }
        driver.FindElement(By.Id("StudentId")).Click();
        driver.FindElement(By.Id("CourseId")).Click();
        driver.FindElement(By.Id("CourseId")).Click();
        {
            string value = driver.FindElement(By.Id("Name")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("Fabiana Salas"));
        }
        {
            string value = driver.FindElement(By.Id("Email")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("fab20@gmail.com"));
        }
        {
            string value = driver.FindElement(By.Id("DepartmentId")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("Artes Plasticas"));
        }
        {
            var element = driver.FindElement(By.Id("Name"));
            Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
            Assert.False(isEditable);
        }
        {
            var element = driver.FindElement(By.Id("Email"));
            Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
            Assert.False(isEditable);
        }
        {
            var element = driver.FindElement(By.Id("DepartmentId"));
            Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
            Assert.False(isEditable);
        }
        driver.FindElement(By.CssSelector(".btn")).Click();
        Assert.That(driver.FindElement(By.CssSelector("p:nth-child(4)")).Text, Is.EqualTo("Saved Successfully!"));
        driver.Close();
    }
}
